# Generated by Django 5.2.1 on 2025-05-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicios', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mostrar', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servicios_inicio',
                'managed': False,
            },
        ),
    ]
