# Generated by Django 5.2.1 on 2025-05-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='chip_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mascota',
            name='historial_medico',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=10),
        ),
    ]
