# Generated by Django 5.2.1 on 2025-05-18 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_mascota_chip_id_mascota_historial_medico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='chip_id',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='historial_medico',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=20)),
                ('rostro', models.ImageField(blank=True, null=True, upload_to='rostros/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
